### GET request to example server
WEBSOCKET wss://video-call-multilingual.onrender.com/
Content-Type: application/json // We use it for highlighting

===
{
  "message": "Hello, server!",
  "repeat": 3
}

###
